# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /user
    
user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /
    
